/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface M29OfflineAlert {
        "description": string;
        "message": string;
        "pulse": boolean;
        "rounded": boolean;
    }
}
declare global {
    interface HTMLM29OfflineAlertElement extends Components.M29OfflineAlert, HTMLStencilElement {
    }
    var HTMLM29OfflineAlertElement: {
        prototype: HTMLM29OfflineAlertElement;
        new (): HTMLM29OfflineAlertElement;
    };
    interface HTMLElementTagNameMap {
        "m29-offline-alert": HTMLM29OfflineAlertElement;
    }
}
declare namespace LocalJSX {
    interface M29OfflineAlert {
        "description"?: string;
        "message"?: string;
        "pulse"?: boolean;
        "rounded"?: boolean;
    }
    interface IntrinsicElements {
        "m29-offline-alert": M29OfflineAlert;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "m29-offline-alert": LocalJSX.M29OfflineAlert & JSXBase.HTMLAttributes<HTMLM29OfflineAlertElement>;
        }
    }
}
